### ISSUE TITLE
能否提供Api接口?

### ISSUE THREAD

**Issue by cooljsz** [NebuTech/BTMiner_NebuTech#10]
想知道这个是参考哪个软件开发的,参数和监控接口和哪个挖矿软件兼容,批量矿机需要批量监控和操作,谢谢

**Comment by nebutech-admin** [comment]
从头开发的，没有参考其他项目代码。
API接口将在后续版本联合矿池协商协议进行研发。

**Comment by cooljsz** [comment]
如果能跟现有主流挖矿软件兼容那就太好了,现有挖矿软件监控和参数格式已经在大范围得到适配了,如果自己多搞一套标准,我相信很多人都会很麻烦.
以上建议仅供参考,感谢你的回复.

**Comment by nebutech-admin** [comment]
第一次写miner，很多周边东西不是很清楚。如果有相关的协议文档可以发给我参考一下

**Comment by cooljsz** [comment]
这个可以说是CUDA Miner的鼻祖
https://github.com/cbuchner1/ccminer
tpruvot的ccminer是现在很流行的miner,里面有api的代码
https://github.com/tpruvot/ccminer
这个项目对程序有详细的介绍,其中命令参数说的比较细致
https://github.com/MSFTserver/RavenMiner

**Comment by cooljsz** [comment]
excavator的api文档写的不错
https://github.com/nicehash/excavator/tree/master/api

**Comment by nebutech-admin** [comment]
好的，API的开发工作量还不小，只能放到后续版本，先保证算力和稳定性。

**Comment by cooljsz** [comment]
能不能先把启动参数调整一下?这样最起码启动和停止可以沿用现有程序

**Comment by principino1984** [comment]
It would be great if you could set the "standard" parameters for the configuration... for example -o instear of --url or -u for the url of the pool, and -u for username and not -U. That would help us with few rigs.

**Comment by nebutech-admin** [comment]
Added API support frmo v6.0
