### ISSUE TITLE
Intensity setting for GPU seems to have no effect

### ISSUE THREAD

**Issue by lacomj** [NebuTech/BTMiner_NebuTech#14]
Running with two 1080 Ti GPUs.  Changing the -i setting from 128 to 2000+ has no impact on the hash rate.  The intensity setting also is not reported on startup, so no way to confirm what value it is using for the intensity setting.

**Comment by nebutech-admin** [comment]
The intensity param dose not take much effect on 1080ti.
However, if you want to be sure the its effect, set it to a very low number you'll see the difference.

**Comment by lacomj** [comment]
Thanks for clarification.  I had not tried below 128.
