### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by jackcui555** [NebuTech/BTMiner_NebuTech#15]
WARN - "{\n    \"error\": [\n        28,\n        \"Invalid share: Low difficulty share\",\n        null\n    ],\n    \"id\": 29,\n    \"jsonrpc\": \"2.0\",\n    \"result\": null\n}\n"

reject shares 
:)

**Comment by nebutech-admin** [comment]
Due to the implementation of this mining algorithm, the common reject rate should be at 1%~3%.
Currently the f2pool has some network congestion issue.
You can try antpool instead to test program.

**Comment by jackcui555** [comment]
i will change me pool to try , thankyou!
