### ISSUE TITLE
v2.0 Error Out of memory

### ISSUE THREAD

**Issue by XfirePaul** [NebuTech/BTMiner_NebuTech#17]
V1.3 on windows works fine for me. (Intel Celeron and 11 GTX 1060 6Gb) ~ 2650 h/s .   PL 70% no OC

With this new v2.0 i get the "cuda error: out of memor (errn_um=2)"

**Comment by nebutech-admin** [comment]
Try tune down the param -i, or add more DDR memory, 8G should works fine for 8 GPUs.

**Comment by XfirePaul** [comment]
-i param does nothing. Upgraded to 8Gb and problem solved but now it gives me another error.
