### ISSUE TITLE
v2.0 Error Out of memory 

### ISSUE THREAD

**Issue by dogtb** [NebuTech/BTMiner_NebuTech#19]
V1.3 run 12 card 1050ti OK but reject more 50%. v2.0 not run 12 card bug With this new v2.0 i get the "cuda error: out of memor (errn_um=2)"

**Comment by nebutech-admin** [comment]
If you have more 8 cards, try tune down -i param, or add more memory, say change from 4G to 8G

**Comment by dogtb** [comment]
I adjusted the -i parameter but the tool was always off.

**Comment by XfirePaul** [comment]
-i param does nothing. Upgraded to 8Gb and problem solved but now it gives me another error.
