### ISSUE TITLE
10 % Dev fee

### ISSUE THREAD

**Issue by PriceTT** [NebuTech/BTMiner_NebuTech#20]
It has been reported that the miner has a [10 % deve fee](https://bitcointalk.org/index.php?topic=3921500.msg39443769#msg39443769).
Could you make it clear to the community what the dev fee actually is.

**Comment by EliotFR** [comment]
After a quick tcpdump, devfee is around 15%.

**Comment by monkins1010** [comment]
Please advertise the baked in dev fee
