### ISSUE TITLE
Windows i3-4170 5x1080ti - 100% cpu usage

### ISSUE THREAD

**Issue by pedro77pl** [NebuTech/BTMiner_NebuTech#21]
Is it normal for this miner to use 100% cpu power on i3-4170? I tested running the single card only, and cpu usage is 23% per card. With 5 cards CPU is actually bottlenecking the system. Miner is running without -C

**Comment by nebutech-admin** [comment]
With -M option, program will also draw significant CPU usage.
If either -M nor -C are set, it's abnormal.
