### ISSUE TITLE
Mining program unexpected exit. Restarting ... 

### ISSUE THREAD

**Issue by jackcui555** [NebuTech/BTMiner_NebuTech#25]
1070TI显卡 12张 B250主板  运行2.0程序报错   使用-d参数运行10卡可以正常运行但是i参数只能设置为默认，7卡i=1024可以正常运行  这个是电脑的CPU配置过低的原因么？ 还是程序不支持10卡以上呢，这套电脑挖别的币一直很正常，一直找不到原因，请帮我分析一下 谢谢

**Comment by linus0001** [comment]
我也用B250+4个1080ti，运行win 2.0不稳定，运行一段时间，系统崩溃重启电脑。CPU,i3 7100。挖其他币也正常。
