### ISSUE TITLE
not run on ubuntu 16.4

### ISSUE THREAD

**Issue by dogtb** [NebuTech/BTMiner_NebuTech#32]
Hi team !
me for running on a system 16.4 driver nvidia 390.67, error will not run. images as error on the driver version
Thanks

**Comment by earthGavinLee** [comment]
update 396.18

**Comment by TheMeasles** [comment]
I have 396.24.02 and it says driver insufficient error 35.

While I'm here... test ran version 1 and 2 and they report hash rates much lower than your reference.

I have 2x1080ti and 3x1070 all of them on 1xPCIE risers
total hash reported varies between 700 and 1000 H/s

Shouldn't this be ~4000 H/s ?

I can put three cards on 4xPCIE or one on 16x on the motherboard... but I am not about to try this until I see it work :)

Thanks for this, if it does fly it will be great

**Comment by TheMeasles** [comment]
OK I selected 396.24.02 from additional drivers in xubuntu 16.04

xubuntu seems to think 396.24.02 is 'in use' but it is not just your miner which does not work

conclusion driver problem is with ubuntu telling me it is 'in use' when it isn't - not your problem.

I'd still like to know how to get those hash rates though

**Comment by TheMeasles** [comment]
all sorted, driver conflicts.... and the new miner displays the right hashrates

Thanks a lot, you deserve your 3% :)
