### ISSUE TITLE
Support for Sophon SS1 Server or Sophon SC1 cards?

### ISSUE THREAD

**Issue by SimonBelmond** [NebuTech/BTMiner_NebuTech#33]
Dear Nebu Tech Team

Sorry for not writing in Chinese. I would like to know if there is any chance you will support Sophon cards? From what I understand they could be ideal for BTM mining. Do you guys see any possibility to support these cards?

Thank you.

Simon

Technical documentation can be found here: https://ivs.bitmain.io/s/nSZuf0F7OfbYVUV

More also here: https://archive.sophon.ai/sophon-prod/drive/SS1_White_Paper%20V1.0.pdf

And here: https://archive.sophon.ai/sophon-prod/drive/SC1_White%20Paper%20V1.0.pdf

**Comment by nebutech-admin** [comment]
Email me
NebuTech@hotmail.com
