### ISSUE TITLE
关于-M参数

### ISSUE THREAD

**Issue by jackcui555** [NebuTech/BTMiner_NebuTech#35]
我的机器为12卡1070TI 以前做别的项目也经常遇见cuda memory error  这个BTM也是 一直在用9卡挖 多了就报错 自从这次更新-M参数后12卡都能流畅运行了 非常稳定，可以单独开发一个小程序解决别的项目的cuda memory error 这个问题么 ，或者可以分享一下怎么解决这个问题的办法 ，非常感谢，期待您的回复

**Comment by nebutech-admin** [comment]
发邮件联系NebuTech@hotmail.com
