### ISSUE TITLE
报错 “Process crashed”

### ISSUE THREAD

**Issue by jackieliujcl** [NebuTech/BTMiner_NebuTech#38]
V3.0在 windows 10上运行一会就报了下面的错误，求解决，谢谢！

GPU Error, try reseting ...
1073741819 "Process crashed"
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!! Mining program unexpected exit. Restarting ... !!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by wwhl123321** [comment]
try v3.3
