### ISSUE TITLE
Frequent Mining pool disconnected:  "The remote host closed the connection"

### ISSUE THREAD

**Issue by SuperCUDA** [NebuTech/BTMiner_NebuTech#41]
I tried the latest 3.3 GPU miner on my 2x GTX1080 card i7 8700 machine.  I have very good network with no issues to any parts of the world.  I tried Antpool, BTCC pool. uuPool and F2Pool.  All of them have the same  Mining pool disconnected:  "The remote host closed the connection" issue after just 2-3 minutes (some times even shorter) of run time.  Also, none of the submitted shared seems to show of my miner accounts (all of which are working perfectly fine with my B3).

Any clue as to what the problem is?  Also, where are the logs located?
Thanks in advance for your help!

**Comment by monkins1010** [comment]
The dev fee is mining on f2pool. That normally connects after a few minutes. But if you say you tried that then must be something else. I'm assuming v3.0 was ok for you? Theres no hash rate improvement in 3.3 versus 3.0

**Comment by SuperCUDA** [comment]
thanks @monkins1010.  No v3.0 didn't work for me either.   Are you saying that because dev fee is mining on f2pool, the miner will need to disconnect from whatever the connected mining pool (other than f2pool) that it is on periodically and switch back and forth?  Where are the logs located?

**Comment by nebutech-admin** [comment]
@SuperCUDA Hi, where is your location? The remote connection closed cound due to 
1. low hashrate which result in no submit in a relative long time, and could cause the pool disconnect.
2. Bad network connection quality, high latency, unstable connection ...

**Comment by SuperCUDA** [comment]
@nebutech-admin Thanks for your quick response. I am in the US, resides in a major city on east coast, with fat internet pipe provided by Comcast.  Gigabit connection to the rest of the world without any problems.  Able to stream multiple HD videos simultaneously.  The console displayed hash rate is fairly consistent at 1200 H/s.  Could you please tell me where are the log files located so I can do some basic troubleshooting?  Thanks!

**Comment by nebutech-admin** [comment]
@SuperCUDA Sorry, there is no debug level log file. The only visible log is the stdout on cmd line.
