### ISSUE TITLE
BTminer_ERROR_Virtual box

### ISSUE THREAD

**Issue by sasukexy** [NebuTech/BTMiner_NebuTech#44]
I downloaded the miner and when I ran it, I kept on getting the same error(see below). I need help, please.
![unknown](https://user-images.githubusercontent.com/36013981/41538855-23d8f32c-7304-11e8-8883-1ad3807e5c81.png)

**Comment by wwhl123321** [comment]
the pic is too small. if you don`t run it on vm .pls turn off hyper-x and uninstall vm software
