### ISSUE TITLE
Miner Unstable: Crashing after 1-15 minutes. (errn_um: 13 & errn_um: 46)

### ISSUE THREAD

**Issue by Meteorite777** [NebuTech/BTMiner_NebuTech#5]
Miner isn't stable.

On desktop with 2 cards directly in PCIEx16 it runs fine; and at higher hashrate.

On mining rigs using risers and 6-8 cards the miner is unstable and crashes after only a few minutes giving CUBLAS errors.

Error num 13 and 46.

![image](https://user-images.githubusercontent.com/6587106/40891702-1fc6b842-6750-11e8-9474-9ec09ab52c7f.png)

**Comment by EliotFR44** [comment]
![image](https://user-images.githubusercontent.com/39886697/40900918-32156c2c-67ce-11e8-9905-f1304d48f489.png)
 same here

**Comment by Meteorite777** [comment]
Your error is different. Easy fix. You need to be updated to current Nvidia driver; it says so in the readme.md. Just update to atleast 397.64 and that will go away.

**Comment by xiaoluozhou** [comment]
This is not about  the Nvidia driver, because I am update to 397.93 .and use 6 cards miner will errn_um: 13.

**Comment by xiaoluozhou** [comment]
感谢回复，也就是说目前来说6卡以上的话是没办法避免error 13吗?
