### ISSUE TITLE
12 gpu

### ISSUE THREAD

**Issue by sw629241** [NebuTech/BTMiner_NebuTech#52]
![image](https://user-images.githubusercontent.com/40855963/42316967-bc1790f4-807d-11e8-9b65-bfd23648252b.png)

在12卡系統上算力落差很大。
G3930
8GB RAM
B250 Mining Expert
nvidia 1063

**Comment by nebutech-admin** [comment]
你的主板BIOS里面，PCIE是GEN2么

**Comment by sw629241** [comment]
v6.0 在12卡的遊戲卡上有很大程度的提升，讚.
使用 config.json 中的 API ，無法讀取數值，使用 CMD 格式 API 正常運作。

**Comment by nebutech-admin** [comment]
config里面的api不管用，这个确认是bug，以后版本修复，不急于更新。
你的12卡现在全部卡的算力都正常不会掉了吧？

**Comment by sw629241** [comment]
![image](https://user-images.githubusercontent.com/40855963/43259123-c4bd1888-9107-11e8-8fc0-55e2e93fe34f.png)
![image](https://user-images.githubusercontent.com/40855963/43259138-ccb78122-9107-11e8-96f8-21385c151d99.png)
第一張圖是 1063 ，可以看出來還是有一、二張卡算力偏低，大概有十多台相同規格，得到的結論差不多。
第二張圖是P106，數值很平均穩定。

v6.0 整體看都有提升算力，在1063的部分，不平均的卡減少了，並有拉高算力。
