### ISSUE TITLE
why cannot run in my Titanx

### ISSUE THREAD

**Issue by zzz0906** [NebuTech/BTMiner_NebuTech#53]
-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.26                 Driver Version: 396.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  Off  | 00000000:02:00.0 Off |                  N/A |
| 22%   53C    P0    75W / 250W |      0MiB / 12212MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  Off  | 00000000:83:00.0 Off |                  N/A |
|  0%   45C    P0    64W / 250W |      0MiB / 12212MiB |      2%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |

CUDA Error: an illegal instruction was encountered (err_no=73)
018-07-07 01:12:22,931 ERROR - GPU Error occured, restart program.
2018-07-07 01:12:23,092 ERROR - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2018-07-07 01:12:23,092 ERROR - Mining program unexpected exit. 
2018-07-07 01:12:23,092 ERROR - 11 "Process crashed"
2018-07-07 01:12:23,092 ERROR - Restarting...

**Comment by nebutech-admin** [comment]
Only pascal and later gpus are supported

**Comment by zzz0906** [comment]
thx
