### ISSUE TITLE
Sorry, this application cannot run under a Virtual Machine

### ISSUE THREAD

**Issue by melody2012** [NebuTech/BTMiner_NebuTech#58]

**Comment by nebutech-admin** [comment]
If you are running on a physical windows machine. Turn off the Hyper V in BIOS settings.

**Comment by 3kynox** [comment]
Hello! I would like to make a review about this here. I am using a virtual machine, but the processor is natively used on my VM, and I use GPU Passthrought to pass natively my graphic card to this virtual machine. Why couldn't I use my hardware to mine?

In my case, this error message that prevent me to use NbMiner is non-relevant.

**Comment by zaptrem** [comment]
This is happening to me as well. Passed-through GPU.
