### ISSUE TITLE
windows 10 home

### ISSUE THREAD

**Issue by AndAntAnd** [NebuTech/BTMiner_NebuTech#66]
When I try to run on windows 10 8 pcs p106-100 cards I get 2 following errors:
1) System can't find MSVCP140.dll
2) System cant't find VCRUNTIME140.dll

The same mistake on p104 miner and 1080ti rigs. 
On all of these miners I use Claymore 11.9 with no problem.

What could be the problem?

**Comment by nebutech-admin** [comment]
The zip packaged a msvc .exe along with the miner, install that will solve yout problem.
