### ISSUE TITLE
56% rejected......

### ISSUE THREAD

**Issue by BattleWoLFz99** [NebuTech/BTMiner_NebuTech#9]
Can you please find the problem and fix it? I was using f2pool and found it such high reject rate.

**Comment by nebutech-admin** [comment]
After work with f2pool, we found the high reject rate due to both miner program bug and f2pool network congestion. Later today or tomorrow we’ll release a new version with bug fix and even more hashrate boost.

**Comment by BattleWoLFz99** [comment]
Thank you, sir.
